# utils

In [ ]:
# import yaml

def podDict(l, i):
    d = dict()
    d['name'] = "pod"+str(i)
    d['cpu'] = int(l[0])
    d['mem'] = int(l[1])
    return d

In [3]:
def nodeDict(l, i):
    d = dict()
    d['name'] = "node"+str(i)
    d['cpu'] = int(l[0])
    d['mem'] = int(l[1])
    d['pnum'] = int(l[2])
    return d

In [4]:
import numpy as np

def get_random_pod_matrix(pod_num, min_v, max_v):
    return np.random.randint(min_v, max_v, (pod_num, 2))
#     return np.random.randint(2, 10, (pod_num, 2))
    
def get_random_node_matrix(node_num, min_v, max_v, equal_to_110 = False):
    nodeList = np.random.randint(min_v, max_v, (node_num, 2))
    if equal_to_110:
        t = np.full( (node_num, 1), 110)
    else:
        t = np.random.randint(80, 110, (node_num, 1))
    return np.c_[nodeList, t]

In [5]:
print(get_random_pod_matrix(2, 3, 6))
print(get_random_node_matrix(9, 100, 200, True))

[[4 5]
 [3 5]]
[[183 177 110]
 [158 164 110]
 [197 137 110]
 [180 118 110]
 [101 185 110]
 [151 148 110]
 [137 164 110]
 [153 198 110]
 [126 177 110]]


# million data
*for the previous data input requirement*

In [8]:
import random

In [64]:
# res = []
node_num = 3
node_max = 10
c = 0
count = 0

while count < 100000:
    d = dict()
    c = c+1
    count = count + 1
    if c == 18000:
        c = 0
        node_num = node_num+1
    p = get_random_pod_matrix(20, 4, 10)
    n = get_random_node_matrix(random.randint(3, 21), 200, 900, True)
    d['Pods'] = p
    d['Nodes'] = n
    res.append(d)
    

In [65]:
len(res)

600000

In [66]:
node_num = 3
node_max = 10
c = 0
count = 0

while count < 200000:
    d = dict()
    c = c+1
    count = count + 1
    if c == 18000:
        c = 0
        node_num = node_num+1
    p = get_random_pod_matrix(20, 50, 100)
    n = get_random_node_matrix(random.randint(3, 21), 300, 500, True)
    d['Pods'] = p
    d['Nodes'] = n
    res.append(d)

In [67]:
len(res)

800000

In [68]:
node_num = 3
node_max = 10
c = 0
count = 0

while count < 100000:
    d = dict()
    c = c+1
    count = count + 1
    if c == 18000:
        c = 0
        node_num = node_num+1
    p = get_random_pod_matrix(20, 50, 100)
    n = get_random_node_matrix(random.randint(10, 21), 800, 900, True)
    d['Pods'] = p
    d['Nodes'] = n
    res.append(d)

In [69]:
len(res)

900000

In [74]:
node_num = 3
node_max = 10
c = 0
count = 0
r = []

while count < 100000:
    d = dict()
    c = c+1
    count = count + 1
    if c == 18000:
        c = 0
        node_num = node_num+1
    p = get_random_pod_matrix(20, 50, 100)
    n = get_random_node_matrix(random.randint(13, 19), 800, 900, True)
    d['Pods'] = p
    d['Nodes'] = n
    r.append(d)

In [75]:
res = res[0:900000]+r

In [13]:
count = 0
r = []

while count < 500000:
    d = dict()
    count = count + 1
    p = get_random_pod_matrix(20, 50, 100)
    n = get_random_node_matrix(10, 800, 900, True)
    d['Pods'] = p
    d['Nodes'] = n
    r.append(d)

# run twice with different params to get 1 million
*for the current 20pods-10nodes data requirement*

In [14]:
count = 0
while count < 500000:
    d = dict()
    count = count + 1
    p = get_random_pod_matrix(20, 50, 100)
    n = get_random_node_matrix(10, 800, 900)
    d['Pods'] = p
    d['Nodes'] = n
    r.append(d)

In [15]:
len(r)

1000000

In [76]:
len(res)

1000000

In [77]:
res[999999]

{'Pods': array([[50, 85],
        [97, 56],
        [77, 54],
        [65, 76],
        [51, 85],
        [83, 79],
        [89, 55],
        [61, 91],
        [68, 51],
        [73, 59],
        [79, 54],
        [84, 83],
        [74, 59],
        [51, 85],
        [91, 54],
        [57, 50],
        [70, 75],
        [56, 92],
        [67, 50],
        [68, 92]]), 'Nodes': array([[866, 814, 110],
        [889, 856, 110],
        [867, 883, 110],
        [885, 857, 110],
        [873, 854, 110],
        [887, 851, 110],
        [894, 870, 110],
        [867, 843, 110],
        [872, 855, 110],
        [880, 847, 110],
        [822, 871, 110],
        [841, 894, 110],
        [858, 860, 110]])}

# generate the million input

In [16]:
data = []
for d in r:
    pods = d['Pods']
    nodes = d['Nodes']
    podList = []
    nodeList = []
    d = dict()

    for i in range(len(pods)):
        t = podDict(pods[i], i)
        podList.append(t)

    for i in range(len(nodes)):
        t = nodeDict(nodes[i], i)
        nodeList.append(t)
    d['Pods'] = podList
    d['Nodes'] = nodeList
    data.append(d)
    

In [17]:
len(data)

1000000

In [18]:
import json

with open('temp.json', 'w') as f:
    json.dump(data, f)