In [1]:
import yaml

def podDict(l, i):
    d = dict()
    d['name'] = "pod"+str(i)
    d['cpu'] = l[0]
    d['mem'] = l[1]
    return d

In [2]:
def nodeDict(l, i):
    d = dict()
    d['name'] = "node"+str(i)
    d['cpu'] = l[0]
    d['mem'] = l[1]
    d['pnum'] = l[2]
    return d

In [15]:
import numpy as np

def get_random_pod_matrix(pod_num):
    return np.random.randint(2, 10, (pod_num, 2))
    
def get_random_node_matrix(node_num):
    nodeList = np.random.randint(2000, 4000, (node_num, 2))
    t = np.random.randint(80, 110, (node_num, 1))
    return np.c_[nodeList, t]

In [31]:
print(get_random_pod_matrix(2))
print(get_random_node_matrix(9))

[[7 3]
 [4 8]]
[[2153 2782   97]
 [2622 2464   86]
 [2378 2499   99]
 [2550 2600  107]
 [2396 2483   96]
 [2850 2440   96]
 [2178 2207  108]
 [2633 2837   83]
 [2112 2994   86]]


# data generate test

In [3]:
res = []

for k, v in load_dict.items():
    for i in v:
        pods = i['input_pods']
        nodes = i['input_nodes']
        podList = []
        nodeList = []
        d = dict(
        
        for i in range(len(pods)):
            t = podDict(pods[i], i)
            podList.append(t)
            
        for i in range(len(nodes)):
            t = nodeDict(nodes[i], i)
            nodeList.append(t)
        d['Pods'] = podList
        d['Nodes'] = nodeList
        res.append(d)

SyntaxError: invalid syntax (<ipython-input-3-20f6b6e5e269>, line 10)

In [39]:
res = []
node_num = 3
node_max = 5
c = 0

while node_num < node_max:
    d = dict()
    c = c+1
    if c == 300:
        c = 0
        node_num = node_num+1
    p = get_random_pod_matrix(20)
    n = get_random_node_matrix(node_num)
    d['Pods'] = p
    d['Nodes'] = n
    res.append(d)
    

# generate yaml file

In [33]:
import json

with open('temp.json', 'r') as f:
    data_list = json.load(f)
print(len(data_list))

5400


In [35]:
res = []
for d in data_list:
    pods = d['Pods']
    nodes = d['Nodes']
    podList = []
    nodeList = []
    d = dict()

    for i in range(len(pods)):
        t = podDict(pods[i], i)
        podList.append(t)

    for i in range(len(nodes)):
        t = nodeDict(nodes[i], i)
        nodeList.append(t)
    d['Pods'] = podList
    d['Nodes'] = nodeList
    res.append(d)
    

In [36]:
len(res)

5400

In [37]:

for i in range(len(res)):
    with open("input_data/pod_space_less_than_110/input_"+str(i)+".yaml", 'w') as f:
        yaml.dump(res[i], f)

## pod space == 110

In [41]:
with open('temp1s.json', 'r') as f:
    data_list = json.load(f)
print(len(data_list))

5400


In [42]:
res = []
for d in data_list:
    pods = d['Pods']
    nodes = d['Nodes']
    podList = []
    nodeList = []
    d = dict()

    for i in range(len(pods)):
        t = podDict(pods[i], i)
        podList.append(t)

    for i in range(len(nodes)):
        t = nodeDict(nodes[i], i)
        nodeList.append(t)
    d['Pods'] = podList
    d['Nodes'] = nodeList
    res.append(d)
    

In [43]:
len(res)

5400

In [44]:

for i in range(len(res)):
    with open("input_data/pod_space_equal_to_110/input_"+str(i)+".yaml", 'w') as f:
        yaml.dump(res[i], f)